[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ash = {version = "0.38.0", default-features=false, features=["linked", "debug", "std"]}
ash-window = "0.13.0"
raw-window-handle = "0.6.2"

window = { path = "../window" }
